EMR/urls.py
"""
Definition of urls for EMR.
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('login.urls')),
    url(r'^patientcontact/', include('patientcontact.urls')),
    url(r'^patientmedicalhistory/', include('patientmedicalhistory.urls')),
    url(r'^patientinsurance/', include('patientinsurance.urls')),
    url(r'^patientmeds/', include('patientmeds.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^admin/', admin.site.urls),
]

dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

patientcontact/urls.py
from django.conf.urls import url

from . import views

app_name = 'patientcontact'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^modifypage/$', views.ModifyView.as_view(), name='modifypage'),
    url(r'^readContactInfo/$', views.readData, name='readContactInfo'),
    url(r'^saveContactInfo/$', views.saveContactInfo, name='saveContactInfo'),
    url(r'^updateContactInfo/$', views.updateContactInfo, name='updateContactInfo'),
]

patientcontact/models.py
from django.db import models

# Create your models here.
class PatientContact(models.Model):
    user_name = models.CharField(max_length=30, default="xxx")
    first_name = models.CharField(max_length=20, default='Jane')
    middle_name = models.CharField(max_length=20, default='Chandler')
    last_name = models.CharField(max_length=20, default='Doe')
    address = models.CharField(max_length=30, default='2662 Cannon Point Ct')
    city = models.CharField(max_length=20, default='Columbus')
    state = models.CharField(max_length=2, default='OH')
    zipCode = models.CharField(max_length=12, default='43209')
    homePhone = models.CharField(max_length=10, default='6144555678')
    cellPhone = models.CharField(max_length=10, default='6144567890')
    email = models.CharField(max_length=30, default='xu.285@franklin.edu')

patientcontact/views.py
from django.shortcuts import render
from django.views import generic
from .models import PatientContact
 
class IndexView(generic.TemplateView):
    template_name = 'patientcontact/index.html'
    
def saveContactInfo(request):
    pc = PatientContact(
        user_name = request.session.get('member_id'),
        first_name = request.POST['contFirstName'],
        middle_name = request.POST['contMiddleName'],
        last_name = request.POST['contLastName'],
        address = request.POST['contAddress'],
        city = request.POST['contCity'],
        state = request.POST['contState'],
        zipCode = request.POST['contZip'],   
        homePhone = request.POST['contPhoneMain'],
        cellPhone = request.POST['contPhoneCell'],
        email = request.POST['contEmail'])
    pc.save()
    return render(request, 'patientinsurance/index.html')

class ModifyView(generic.TemplateView):
    template_name = 'patientcontact/modify.html'
    
def readData(request):
    if request.session.get('member_id'):
        contact = PatientContact.objects \
            .filter(user_name__exact = request.session.get('member_id')).values();
        return render(request, "patientcontact/modify.html", {"contact_list": contact,})
    return render(request, "login/index.html")

def updateContactInfo(request):
    if request.session.get('member_id'):
        pc = PatientContact.objects.get(user_name=request.session.get('member_id')) 
        pc.user_name = request.session.get('member_id')
        pc.first_name = request.POST['contFirstName']
        pc.middle_name = request.POST['contMiddleName']
        pc.last_name = request.POST['contLastName']
        pc.address = request.POST['contAddress']
        pc.city = request.POST['contCity']
        pc.state = request.POST['contState']
        pc.zipCode = request.POST['contZip']
        pc.homePhone = request.POST['contPhoneMain']
        pc.cellPhone = request.POST['contPhoneCell']
        pc.email = request.POST['contEmail']
        pc.save()
        return render(request, 'dashboard/index.html')
    else:
        return render(request, 'login/index.html')

patientcontact/templates/patientcontact/index.html
<!doctype html>
<html>
<head>
{% load static %}
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="{% static 'patientcontact/jslib/jquery-ui.min.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'patientcontact/jslib/jquery-ui.theme.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'patientcontact/style.css' %}" />
<script src="{% static 'patientcontact/jslib/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'patientcontact/jslib/jquery.validate.js' %}"></script>
<script src="{% static 'patientcontact/jslib/jquery-ui.min.js' %}"></script>

<script type="text/javascript">

$().ready(function() {
	
	$("#patientContactInfoConfirm").dialog({ 
		autoOpen: false,
		resizable: true,
		modal: false,
		height: "auto",
		width: 600
	});
	
	$( "#contState" ).selectmenu({
		width: 270
	});
	
	// validate contact form on keyup and submit
	var validator = $("#patientContactForm").validate({
		errorClass: "warning",
		rules: {
			contFirstName: "required",
			contLastName: "required",
			contAddress: {
				required: true,
				minlength: 10
			},
			contCity: {
				required: true,
				minlength: 5
			},
			contState: {
				required: true
			},
			contZip: {
				required: true,
				minlength: 5
			},
			contPhoneMain: {
				required: true,
				minlength: 10
			},
			contPhoneCell: {
				required: true,
				minlength: 10
			},
			contEmail: {
				required: true,
				email: true
			}
		},
		messages: {
			contFirstName: "Please enter your first name!",
			contLastName: "Please enter your last name!",
			contAddress: {
				required: "Please enter an address!",
				minlength: "Your address must consist of at least 10 characters"
			},
			contCity: {
				required: "Please enter your city!",
				minlength: "Your city must be at least 5 characters long!"
			},
			contState: {
				required: "Please select your state!"
			},
			contZip: {
				required: "Please enter your zipcode!",
				minlength: "Your zipcode must be a 5 digit number!"
			},
			contPhoneMain: {
				required: "Please enter your home phone!",
				minlength: "Your home phone number should be 10 digits!"
			},
			contPhoneCell: {
				required: "Please enter your cell phone!",
				minlength: "Your cell phone number should be 10 digits!"
			},
			contEmail: {
				required: "Please enter your email address!",
				email: "Please enter a valid email address!"
			}
		},
		errorContainer: $("#errorContainer"),
		errorLabelContainer: $("#errorContainer ul"),
		wrapper: "li"
	});
	
    $("#patientContactForm").on('submit', function (e) {
        e.preventDefault();
		if (validator.form()) {
			$.ajax({
				type:'post',
				data:$('#patientContactForm').serialize(),
				success:function(){}
			});
			var form1 = $('#patientContactForm'), 
				form2 = $('#patientContactInfoConfirmForm'); 
			$(':input[name]', form2).val(function(){
				return $(':input[name='+ this.name +']', form1).val();
			});
			$("#patientContactInfoConfirm").dialog("open");
		}
	});
	
});

</script>
</head>

<body>
<div class="contactinfo-page">
      <div class="form">
<form id="patientContactForm">
{% csrf_token %}
<table class="cols3">
  <tr>
    <td colspan="4"> <h1><div align="center"> Contact Information </div></h1></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><div align="right">First Name:</div></td>
    <td><input name="contFirstName" type="text" id="contFirstName" size="40" /></td>
    <td rowspan="10">
        <div id="errorContainer">
            <p>Please correct the following errors and try again:</p>
            <ul/>
        </div>
    </td>
  </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Middle Name:</div></td>
    <td><input name="contMiddleName" type="text" id="contMiddleName" size="40" /></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Last Name:</div></td>
    <td><input name="contLastName" type="text" id="contLastName" size="40" /></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Address:</div></td>
    <td><input name="contAddress" type="text" id="contAddress" size="40" /></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">City:</div></td>
    <td><input name="contCity" type="text" id="contCity" size="40" /></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">State:</div></td>
    <td>
    <select name="contState" id="contState">
        <option disabled selected>-Select-</option>
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>
        <option value="AZ">Arizona</option>
        <option value="AR">Arkansas</option>
        <option value="CA">California</option>
        <option value="CO">Colorado</option>
        <option value="CT">Connecticut</option>
        <option value="DE">Delaware</option>
        <option value="DC">District Of Columbia</option>
        <option value="FL">Florida</option>
        <option value="GA">Georgia</option>
        <option value="HI">Hawaii</option>
        <option value="ID">Idaho</option>
        <option value="IL">Illinois</option>
        <option value="IN">Indiana</option>
        <option value="IA">Iowa</option>
        <option value="KS">Kansas</option>
        <option value="KY">Kentucky</option>
        <option value="LA">Louisiana</option>
        <option value="ME">Maine</option>
        <option value="MD">Maryland</option>
        <option value="MA">Massachusetts</option>
        <option value="MI">Michigan</option>
        <option value="MN">Minnesota</option>
        <option value="MS">Mississippi</option>
        <option value="MO">Missouri</option>
        <option value="MT">Montana</option>
        <option value="NE">Nebraska</option>
        <option value="NV">Nevada</option>
        <option value="NH">New Hampshire</option>
        <option value="NJ">New Jersey</option>
        <option value="NM">New Mexico</option>
        <option value="NY">New York</option>
        <option value="NC">North Carolina</option>
        <option value="ND">North Dakota</option>
        <option value="OH">Ohio</option>
        <option value="OK">Oklahoma</option>
        <option value="OR">Oregon</option>
        <option value="PA">Pennsylvania</option>
        <option value="RI">Rhode Island</option>
        <option value="SC">South Carolina</option>
        <option value="SD">South Dakota</option>
        <option value="TN">Tennessee</option>
        <option value="TX">Texas</option>
        <option value="UT">Utah</option>
        <option value="VT">Vermont</option>
        <option value="VA">Virginia</option>
        <option value="WA">Washington</option>
        <option value="WV">West Virginia</option>
        <option value="WI">Wisconsin</option>
        <option value="WY">Wyoming</option>
	</select>    </td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Zip:</div></td>
    <td><input name="contZip" type="text" id="contZip" size="40" /></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Phone (main):</div></td>
    <td><input name="contPhoneMain" type="text" id="contPhoneMain" size="40" /></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Phone (cell):</div></td>
    <td><input name="contPhoneCell" type="text" id="contPhoneCell" size="40" /></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">E-mail:</div></td>
    <td><input name="contEmail" type="text" id="contEmail" size="40" /></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
    <td>
   		<div style="width:300px; margin-top:5px;">
            <input type="submit" value="Save">
            <a class="message" href="{% url 'dashboard:index'%}">
                <div style="width:110px; display:inline-block; margin-left:4px; padding: 14px; text-align:center; border:1px solid #4CAF50">
                    Dashboard
                </div>
            </a>
        </div>
    </td>
    <td>&nbsp;</td>
  </tr>
</table>
</form>
</div>
</div>

<!--below is confirmation dialog-->
<div id="patientContactInfoConfirm" title="Confirmation">
<div class="contactinfo-page">
<div class="form">
<form id="patientContactInfoConfirmForm" action="{% url 'patientcontact:saveContactInfo'%}" method="post">
{% csrf_token %}
<table class="cols2">
  <tr>
    <td><div align="right">First Name:</div></td>
    <td><input name="contFirstName" type="text" id="contFirstName" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Middle Name:</div></td>
    <td><input name="contMiddleName" type="text" id="contMiddleName" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Last Name:</div></td>
    <td><input name="contLastName" type="text" id="contLastName" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Address:</div></td>
    <td><input name="contAddress" type="text" id="contAddress" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">City:</div></td>
    <td><input name="contCity" type="text" id="contCity" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">State:</div></td>
    <td><input name="contState" type="text" id="contState" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Zip:</div></td>
    <td><input name="contZip" type="text" id="contZip" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Phone (main):</div></td>
    <td><input name="contPhoneMain" type="text" id="contPhoneMain" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Phone (cell):</div></td>
    <td><input name="contPhoneCell" type="text" id="contPhoneCell" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">E-mail:</div></td>
    <td><input name="contEmail" type="text" id="contEmail" size="40" /></td>
  </tr>
  <tr>
  	<td></td>
    <td> <input type="submit" value="Save"/> </td>
  </tr>
</table>
</form>
</div>
</div>
</div>
</body>
</html>

patientcontact/templates/patientcontact/modify.html
<!doctype html>
<html>
<head>
{% load static %}
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="{% static 'patientcontact/jslib/jquery-ui.min.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'patientcontact/jslib/jquery-ui.theme.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'patientcontact/style.css' %}" />
<script src="{% static 'patientcontact/jslib/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'patientcontact/jslib/jquery.validate.min.js' %}"></script>
<script src="{% static 'patientcontact/jslib/jquery-ui.min.js' %}"></script>

<script type="text/javascript">

$(document).ready(function() {
	
	$("#patientContactInfoConfirm").dialog({ 
		autoOpen: false,
		resizable: true,
		modal: false,
		height: "auto",
		width: 600
	});
	
	// validate contact form on keyup and submit
	var validator = $("#patientContactForm").validate({
		errorClass: "warning",
		rules: {
			contFirstName: "required",
			contLastName: "required",
			contAddress: {
				required: true,
				minlength: 10
			},
			contCity: {
				required: true,
				minlength: 5
			},
			contState: {
				required: true
			},
			contZip: {
				required: true,
				minlength: 5
			},
			contPhoneMain: {
				required: true,
				minlength: 10
			},
			contPhoneCell: {
				required: true,
				minlength: 10
			},
			contEmail: {
				required: true,
				email: true
			}
		},
		messages: {
			contFirstName: "Please enter your first name!",
			contLastName: "Please enter your last name!",
			contAddress: {
				required: "Please enter an address!",
				minlength: "Your address must consist of at least 10 characters"
			},
			contCity: {
				required: "Please enter your city!",
				minlength: "Your city must be at least 5 characters long!"
			},
			contState: {
				required: "Please select your state!"
			},
			contZip: {
				required: "Please enter your zipcode!",
				minlength: "Your zipcode must be a 5 digit number!"
			},
			contPhoneMain: {
				required: "Please enter your home phone!",
				minlength: "Your home phone number should be 10 digits!"
			},
			contPhoneCell: {
				required: "Please enter your cell phone!",
				minlength: "Your cell phone number should be 10 digits!"
			},
			contEmail: {
				required: "Please enter your email address!",
				email: "Please enter a valid email address!"
			}
		},
		errorContainer: $("#errorContainer"),
		errorLabelContainer: $("#errorContainer ul"),
		wrapper: "li"
	});
	
    $("#patientContactForm").on('submit', function (e) {
        e.preventDefault();
		if (validator.form()) {
			$.ajax({
				type:'post',
				data:$('#patientContactForm').serialize(),
				success:function(){}
			});
			var form1 = $('#patientContactForm'), 
				form2 = $('#patientContactInfoConfirmForm'); 
			$(':input[name]', form2).val(function(){
				return $(':input[name='+ this.name +']', form1).val();
			});
			$("#patientContactInfoConfirm").dialog("open");
		}
	});
	
});

</script>
</head>

<body>
{% if contact_list %}
	{% for contact in contact_list %}
<div class="contactinfo-page">
      <div class="form">
<form id="patientContactForm">
{% csrf_token %}

<table class="cols3">
  <tr>
    <td colspan="4"> <h1><div align="center">Patient's Contact Information </div></h1></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><div align="right">First Name:</div></td>
    <td><input name="contFirstName" type="text" id="contFirstName" size="40" value="{{ contact.first_name }}"/></td>
    <td rowspan="10">
        <div id="errorContainer">
            <p>Please correct the following errors and try again:</p>
            <ul/>
        </div>
    </td>
  </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Middle Name:</div></td>
    <td><input name="contMiddleName" type="text" id="contMiddleName" size="40" value="{{ contact.middle_name }}"/></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Last Name:</div></td>
    <td><input name="contLastName" type="text" id="contLastName" size="40" value="{{ contact.last_name }}"/></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Address:</div></td>
    <td><input name="contAddress" type="text" id="contAddress" size="40" value="{{ contact.address}}"/></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">City:</div></td>
    <td><input name="contCity" type="text" id="contCity" size="40" value="{{ contact.city }}"/></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">State:</div></td>
    <td>
    <script type="text/javascript">
		$(document).ready(function() {	
			$( "#contState" ).val('{{contact.state}}');
			$( "#contState" ).selectmenu();
		});
	</script>
    <select name="contState" id="contState">
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>
        <option value="AZ">Arizona</option>
        <option value="AR">Arkansas</option>
        <option value="CA">California</option>
        <option value="CO">Colorado</option>
        <option value="CT">Connecticut</option>
        <option value="DE">Delaware</option>
        <option value="DC">District Of Columbia</option>
        <option value="FL">Florida</option>
        <option value="GA">Georgia</option>
        <option value="HI">Hawaii</option>
        <option value="ID">Idaho</option>
        <option value="IL">Illinois</option>
        <option value="IN">Indiana</option>
        <option value="IA">Iowa</option>
        <option value="KS">Kansas</option>
        <option value="KY">Kentucky</option>
        <option value="LA">Louisiana</option>
        <option value="ME">Maine</option>
        <option value="MD">Maryland</option>
        <option value="MA">Massachusetts</option>
        <option value="MI">Michigan</option>
        <option value="MN">Minnesota</option>
        <option value="MS">Mississippi</option>
        <option value="MO">Missouri</option>
        <option value="MT">Montana</option>
        <option value="NE">Nebraska</option>
        <option value="NV">Nevada</option>
        <option value="NH">New Hampshire</option>
        <option value="NJ">New Jersey</option>
        <option value="NM">New Mexico</option>
        <option value="NY">New York</option>
        <option value="NC">North Carolina</option>
        <option value="ND">North Dakota</option>
        <option value="OH">Ohio</option>
        <option value="OK">Oklahoma</option>
        <option value="OR">Oregon</option>
        <option value="PA">Pennsylvania</option>
        <option value="RI">Rhode Island</option>
        <option value="SC">South Carolina</option>
        <option value="SD">South Dakota</option>
        <option value="TN">Tennessee</option>
        <option value="TX">Texas</option>
        <option value="UT">Utah</option>
        <option value="VT">Vermont</option>
        <option value="VA">Virginia</option>
        <option value="WA">Washington</option>
        <option value="WV">West Virginia</option>
        <option value="WI">Wisconsin</option>
        <option value="WY">Wyoming</option>
	</select>    
    </td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Zip:</div></td>
    <td><input name="contZip" type="text" id="contZip" size="40" value="{{ contact.zipCode }}"/></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Phone (main):</div></td>
    <td><input name="contPhoneMain" type="text" id="contPhoneMain" size="40" value="{{ contact.homePhone }}"/></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">Phone (cell):</div></td>
    <td><input name="contPhoneCell" type="text" id="contPhoneCell" size="40" value="{{ contact.cellPhone }}"/></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
    <td><div align="right">E-mail:</div></td>
    <td><input name="contEmail" type="text" id="contEmail" size="40" value="{{ contact.email }}"/></td>
    </tr>
  <tr>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
    <td>
   		<div style="width:300px; margin-top:5px;">
            <input type="submit" value="Save">
            <a class="message" href="{% url 'dashboard:index'%}">
                <div style="width:110px; display:inline-block; margin-left:4px; padding: 14px; text-align:center; border:1px solid #4CAF50">
                    Dashboard
                </div>
            </a>
        </div>
    </td>
    <td>&nbsp;</td>
  </tr>
</table>

</form>
</div>
</div>

<!--below is confirmation dialog-->
<div id="patientContactInfoConfirm" title="Confirmation">
<div class="contactinfo-page">
<div class="form">
<form id="patientContactInfoConfirmForm" action="{% url 'patientcontact:updateContactInfo'%}" method="post">
{% csrf_token %}
<table class="cols2">
  <tr>
    <td><div align="right">First Name:</div></td>
    <td><input name="contFirstName" type="text" id="contFirstName" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Middle Name:</div></td>
    <td><input name="contMiddleName" type="text" id="contMiddleName" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Last Name:</div></td>
    <td><input name="contLastName" type="text" id="contLastName" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Address:</div></td>
    <td><input name="contAddress" type="text" id="contAddress" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">City:</div></td>
    <td><input name="contCity" type="text" id="contCity" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">State:</div></td>
    <td><input name="contState" type="text" id="contState" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Zip:</div></td>
    <td><input name="contZip" type="text" id="contZip" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Phone (main):</div></td>
    <td><input name="contPhoneMain" type="text" id="contPhoneMain" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">Phone (cell):</div></td>
    <td><input name="contPhoneCell" type="text" id="contPhoneCell" size="40" /></td>
  </tr>
  <tr>
    <td><div align="right">E-mail:</div></td>
    <td><input name="contEmail" type="text" id="contEmail" size="40" /></td>
  </tr>
  <tr>
  	<td></td>
    <td> <input type="submit" value="Save"/> </td>
  </tr>
</table>
</form>
</div>
</div>
</div>
	{% endfor %}
{% endif %}
</body>
</html>