EMR/urls.py
"""
Definition of urls for EMR.
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('login.urls')),
    url(r'^patientcontact/', include('patientcontact.urls')),
    url(r'^patientmedicalhistory/', include('patientmedicalhistory.urls')),
    url(r'^patientinsurance/', include('patientinsurance.urls')),
    url(r'^patientmeds/', include('patientmeds.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^admin/', admin.site.urls),
]

dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

login/urls.py
from django.conf.urls import url

from . import views
from django.urls import include, path

app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^chgpwdpage/$', views.changePwdPage, name='changepwdpage'),
    url(r'^newuser/$', views.newUser, name='newuser'),
    url(r'^login/?$', views.login, name="verify"),
    url(r'^createuser/?$', views.createUser, name="createuser"),
    url(r'^changepwd/?$', views.changePwd, name="changepwd"),
    url(r'^logoff/?$', views.logoff, name="logoff"),
]

login/models.py
from django.db import models

# Create your models here.
class PatientLogin(models.Model):
    user_name = models.CharField(max_length=30, default='Jane')
    email = models.CharField(max_length=30, default='xxx@gmail.com')
    password = models.CharField(max_length=30, default='xxxx')

login/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import PatientLogin

# Create your views here.
def index(request):
    return render(request, "login/index.html")

def newUser(request): 
    return render(request, "login/newUser.html")

def changePwdPage(request):
    if request.session.get('member_id'):
        return render(request, "login/changepwd.html")
    return render(request, "login/index.html")  
    
def login(request):
    users = PatientLogin.objects.all() \
            .filter(user_name__exact = request.POST['user'], password__exact = request.POST['pwd']).values();
    if users.count() != 1:  
        return HttpResponse("error")
    request.session['member_id'] = request.POST['user']
    request.session.set_expiry(180)
    return HttpResponse("success")

def changePwd(request):
    if request.session.get('member_id'):   
        users = PatientLogin.objects.get(user_name=request.session.get('member_id'))
        if users.password == request.POST['oldpwd']:
            users.password = request.POST['newpwd']
            users.save()
            return HttpResponse("success")
        else:    
            return HttpResponse("error")     
    else:
        return render(request, "login/index.html")

def createUser(request):
    users = PatientLogin.objects.all() \
            .filter(user_name__exact = request.POST['user']).values();
    if users.count() == 0:
        pl = PatientLogin(
            user_name = request.POST['user'],
            email = request.POST['email'],
            password = request.POST['pwd'])
        pl.save()
        request.session['member_id'] = request.POST['user']
        return HttpResponse("success")
    return HttpResponse("error")

def logoff(request):
    del request.session['member_id']
    request.session.modified = True
    return render(request, "login/index.html")

login/templates/login/changepwd.html
<!doctype html>
<html>
<head>
	{% load static %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
    <script src="{% static 'login/jslib/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'login/jslib/jquery.validate.min.js' %}"></script>
    <script src="{% static 'login/jslib/jquery-ui.min.js' %}"></script>
    <script type="text/javascript">
		$(document).ready(function() {

			$("#resetPwdform").on('submit', function(e) {
				if ($("#resetPwdform").valid()) {
					e.preventDefault();
					$.ajax({
						type:"post",
						url: "{% url 'login:changepwd'%}",
						data: $("#resetPwdform").serialize(),
						success:function(data){
							if(data === "success")
								window.location.replace("/dashboard");
							else
								document.getElementById("error").innerHTML = "The old password is incorrect!.";
						}
					});
				}
			});
			
			$("#resetPwdform").validate({
				rules: {
					oldpwd: {
						required: true,
						minlength: 6
					},
					newpwd: {
						required: true,
						minlength: 6
					},
					newpwdconfirm: {
						required: true,
						equalTo: "#newpwd",
						minlength: 6
					}
				},
				messages: {
					oldpwd: {
						required: "The old password is required",
						minlength: "The password has to be at least 6 characters!"
					},
					newpwd: {
						required: "The new password is required!",
						minlength: "The password has to be 6 digits."
					},
					newpwdconfirm: {
						required: "The password confirmation is required!",
						minlength: "The password has to be 6 digits.",
						equalTo: "Please confirm your password!"
					}
				}
			});
			
		});
		
	</script>
</head>
<body>
    
    <div class="login-page">
      <div class="form">
		  <form id="resetPwdform" method="post">
          	  {% csrf_token %}
              <span id="error"></span>
              <input type="password" placeholder="old password" id="oldpwd" name="oldpwd" />
              <input type="password" placeholder="new password" id="newpwd" name="newpwd" />
              <input type="password" placeholder="new password confirm" id="newpwdconfirm" name="newpwdconfirm" />
              <input type="submit" value="Save" />
              <p class="message"><a href="{% url 'dashboard:index'%}">Dashboard</a></p>
		  </form>
      </div>
    </div>
    
</body>
</html>

login/templates/login/index.html
<!doctype html>
<html>
<head>
	{% load static %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
    <script src="{% static 'login/jslib/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'login/jslib/jquery.validate.min.js' %}"></script>
    <script src="{% static 'login/jslib/jquery-ui.min.js' %}"></script>
    <script type="text/javascript">
		$(document).ready(function() {
			setTimeout(function() {
				$('#splash').fadeOut(1000);
			}, 2000);
			
			$("#loginform").on('submit', function(e) {
				if ($("#loginform").valid()) {
					e.preventDefault();
					$.ajax({
						type:"post",
						url: "{% url 'login:verify'%}",
						data: $("#loginform").serialize(),
						success:function(data){
							if(data === "success")
								window.location.replace("/dashboard");
							else
								document.getElementById("error").innerHTML = "Error! Please contact administrator.";
						}
					});
				}
			});
			
		});
		
	</script>
</head>
<body>
	<div id="splash">
    	<center><img src="{% static 'login/EMR-splash.jpg'%}" /></center>
	</div>
    
    <div class="login-page">
      <div class="form">
		  <form id="loginform" method="post">
          	  {% csrf_token %}
              <span id="error"></span>
              <input type="text" placeholder="username" id="user" name="user" required/>
              <input type="password" placeholder="password" id="pwd" name="pwd" required/>
              <input type="submit" value="Login" />
              <p class="message">Not registered? <a href="{% url 'login:newuser'%}">Create an account</a></p>
		  </form>
      </div>
    </div>
    
</body>
</html>

login/templates/login/newUser.html
<!doctype html>
<html>
<head>
	{% load static %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
    <script src="{% static 'login/jslib/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'login/jslib/jquery.validate.min.js' %}"></script>
    <script src="{% static 'login/jslib/jquery-ui.min.js' %}"></script>
    <script type="text/javascript">
		$(document).ready(function() {

			$("#loginform").on('submit', function(e) {
				if ($("#loginform").valid()) {
					e.preventDefault();
					$.ajax({
						type:"post",
						url: "{% url 'login:createuser'%}",
						data: $("#loginform").serialize(),
						success:function(data){
							if(data === "success")
								window.location.replace("/patientcontact");
							else
								document.getElementById("error").innerHTML = "The user name is already used!.";
						}
					});
				}
			});
			
			$("#loginform").validate({
				rules: {
					user: {
						required: true,
						minlength: 6
					},
					email: {
						required: true,
						email: true
					},
					pwd: {
						required: true,
						minlength: 6
					},
					pwdconfirm: {
						required: true,
						equalTo: "#pwd",
						minlength: 6
					}
				},
				messages: {
					user: {
						required: "The user name is required",
						minlength: "The user name has to be at least 6 characters!"
					},
					email: {
						required: "The email is required",
						email: "Please input a valid email address!"
					},
					pwd: {
						required: "The password is required!",
						minlength: "The password has to be 6 digits."
					},
					pwdconfirm: {
						required: "The password confirmation is required!",
						minlength: "The password has to be 6 digits.",
						equalTo: "Please confirm your password!"
					}
				}
			});
			
		});
		
	</script>
</head>
<body>
    
    <div class="login-page">
      <div class="form">
		  <form id="loginform" method="post">
          	  {% csrf_token %}
              <span id="error"></span>
              <input type="text" placeholder="username" id="user" name="user" />
              <input type="text" placeholder="email" id="email" name="email" />
              <input type="password" placeholder="password" id="pwd" name="pwd" />
              <input type="password" placeholder="password confirm" id="pwdconfirm" name="pwdconfirm" />
              <input type="submit" value="Save" />
              <p class="message"><a href="{% url 'login:index'%}">Home Page</a></p>
		  </form>
      </div>
    </div>
    
</body>
</html>