EMR/urls.py
"""
Definition of urls for EMR.
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('login.urls')),
    url(r'^patientcontact/', include('patientcontact.urls')),
    url(r'^patientmedicalhistory/', include('patientmedicalhistory.urls')),
    url(r'^patientinsurance/', include('patientinsurance.urls')),
    url(r'^patientmeds/', include('patientmeds.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^admin/', admin.site.urls),
]

dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

login/urls.py
from django.conf.urls import url

from . import views
from django.urls import include, path

app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^chgpwdpage/$', views.changePwdPage, name='changepwdpage'),
    url(r'^newuser/$', views.newUser, name='newuser'),
    url(r'^login/?$', views.login, name="verify"),
    url(r'^createuser/?$', views.createUser, name="createuser"),
    url(r'^changepwd/?$', views.changePwd, name="changepwd"),
    url(r'^logoff/?$', views.logoff, name="logoff"),
]

patientcontact/urls.py
from django.conf.urls import url

from . import views

app_name = 'patientcontact'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^modifypage/$', views.ModifyView.as_view(), name='modifypage'),
    url(r'^readContactInfo/$', views.readData, name='readContactInfo'),
    url(r'^saveContactInfo/$', views.saveContactInfo, name='saveContactInfo'),
    url(r'^updateContactInfo/$', views.updateContactInfo, name='updateContactInfo'),
]

patientinsurance/urls.py
from django.conf.urls import url

from . import views

app_name = 'patientinsurance'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^saveInsurInfo/$', views.saveInsurInfo, name='saveInsurInfo'),
    url(r'^modifyInsurInfo/$', views.modifyInsurInfo, name='modifyInsurInfo'),
    url(r'^modifypage/$', views.ModifyView.as_view(), name='modifypage'),
    url(r'^modifypage2/$', views.Modify2View.as_view(), name='modifypage2'),
    url(r'^readInsInfo/$', views.readData, name='readInsInfo'),
]

patientmeds/urls.py
from django.conf.urls import url
from . import views
from .views import Meds

app_name = 'patientmeds'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^api/?$', Meds.as_view()),
    url(r'^api/(?P<patientmeds_id>[0-9]+)/?$', Meds.as_view()),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    request.session.set_expiry(300)
    return render(request, "dashboard/index.html")

dashboard/templates/dashboard/dashboard.html
<!doctype html>
<html>
<head>
	{% load static %}
    <meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard/style.css' %}" />
</head>
<body>
	<div class="dashboard-page">
	<div class="form">
    
	<table>
	<tr>
		<td><button>User Information</button></td>
		<td><button>Contact Information</button></td>
		<td><button>Insurance Information</button></td>
	</tr>
	<tr>
		<td><button>Medical History</button></td>
		<td><button onclick="window.location.replace('/patientmeds');">Medications</button></td>
		<td><button onclick="window.location.replace('/login');">Log out</button></td>
	</tr>
	</table>

	</div>
	</div>
</body>
</html>

dashboard/templates/dashboard/index.html
<!doctype html>
<html>
<head>
	{% load static %}
    <meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard/style.css' %}" />
    <script src="{% static 'dashboard/jslib/jquery-3.1.1.min.js' %}"></script>
    <script>
    $(document).ready( function() {
		
		$("button").first().focus();
		stopPropagation("button", "mouseout");
		
		function stopPropagation(id, event) {
			$(id).on(event, function(e) {
				e.stopPropagation();
				return false;
			});
		}

		$(document).mousedown(function(e) {
			if(e.target.nodeName != "BUTTON") {
				e.stopImmediatePropagation();
				e.preventDefault();
			}
		});
		
		$(".dashboard-page").keydown(function(e) {
			switch(e.which) {
				case 37: { // left
					var $focusedElem = $(":focus");
					var btnID = $focusedElem.attr('id') 
					if ( btnID == 2) {
						$("#1").focus();
					}
					else if (btnID == 1) {
						$("#0").focus();
					}
					else if (btnID == 5) {
						$("#4").focus();
					}
					else if (btnID == 4) {
						$("#3").focus();
					}
					break;
				}
		
				case 38: { // up
					var $focusedElem = $(":focus");
					var btnID = $focusedElem.attr('id') 
					if (btnID == 3) {
						$("#0").focus();
					}
					else if (btnID == 4) {
						$("#1").focus();
					}
					else if (btnID == 5) {
						$("#2").focus();
					}
					break;
				}
				case 39: { // right
					var $focusedElem = $(":focus");
					var btnID = $focusedElem.attr('id') 
					if (btnID == 0) {
						$("#1").focus();
					}
					else if (btnID == 1) {
						$("#2").focus();
					}
					else if (btnID == 3) {
						$("#4").focus();
					}
					else if (btnID == 4) {
						$("#5").focus();
					}
					break;
				}
		
				case 40: { // down
					var $focusedElem = $(":focus");
					var btnID = $focusedElem.attr('id') 
					if (btnID == 0) {
						$("#3").focus();
					}
					else if (btnID == 1) {
						$("#4").focus();
					}
					else if (btnID == 2) {
						$("#5").focus();
					}
					break;
				}	
		
				default: return; // exit this handler for other keys
			}
			e.preventDefault(); // prevent the default action (scroll / move caret)
		});

    });
    </script>
</head>
<body>
	<div class="dashboard-page">
	<div class="form">

	<table>
	<tr>
		<td><button id="0" onclick='window.location.replace("{% url 'login:changepwdpage' %}");'>Change Password</button></td>
		<td><button id="1" onclick='window.location.replace("{% url 'patientcontact:readContactInfo' %}");'>Contact Information</button></td>
		<td><button id="2" onclick='window.location.replace("{% url 'patientinsurance:readInsInfo' %}");'>Insurance Information</button></td>
	</tr>
	<tr>
		<td><button id="3" onclick='window.location.replace("{% url 'patientmedicalhistory:readMedHisInfo' %}");'>Medical History</button></td>
		<td><button id="4" onclick='window.location.replace("{% url 'patientmeds:index' %}");'>Medications</button></td>
		<td><button id="5" onclick='window.location.replace("{% url 'login:logoff' %}");'>Log out</button></td>
	</tr>
	</table>

	</div>
	</div>
</body>
</html>