EMR/urls.py
"""
Definition of urls for EMR.
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('login.urls')),
    url(r'^patientcontact/', include('patientcontact.urls')),
    url(r'^patientmedicalhistory/', include('patientmedicalhistory.urls')),
    url(r'^patientinsurance/', include('patientinsurance.urls')),
    url(r'^patientmeds/', include('patientmeds.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^admin/', admin.site.urls),
]

dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

patientmedicalhistory/urls.py
from django.conf.urls import url

from . import views

app_name = 'patientmedicalhistory'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^saveMedHistoryInfo/$', views.saveMedHistory, name='saveMedHistoryInfo'),
    url(r'^readMedHisInfo/$', views.readData, name='readMedHisInfo'),
]

patientmedicalhistory/models.py
from django.db import models

# Create your models here.

class PatientMedHistory(models.Model):
    user_name = models.CharField(max_length=30, default='Jane')
    info_type = models.CharField(max_length=30, default='symptoms')
    med_history = models.CharField(max_length=30, default='Fever')

class MedHistoryInfo(models.Model):
    med_history_id = models.IntegerField(default=0)
    med_history = models.CharField(max_length=100, default='symptoms')
    label = models.CharField(max_length=100, default='symptoms')
    type = models.CharField(max_length=100, default='symptoms')

patientmedicalhistory/views.py
#from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from .models import PatientMedHistory
from .models import MedHistoryInfo

class IndexView(generic.TemplateView):
    template_name = 'patientmedicalhistory/index.html'

def saveMedHistory(request):
    if request.session.get('member_id'):
        user = request.session.get('member_id')
        pat_medHis = PatientMedHistory.objects \
            .filter(user_name__exact = user);
        fields = request.POST 
        if pat_medHis.count() == 0:
            for field in fields:
                field_val = request.POST[field]
                if 'Info' not in field and field_val == '1': 
                    if (field + 'Info') in fields:
                        field_text = fields[field + 'Info']
                    else:
                        field_text = field_val

                    pm = PatientMedHistory(
                        user_name = user,
                        info_type = field,
                        med_history = field_text)
                    pm.save()
            return render(request, 'patientmeds/index.html')
        else:
            for field in fields:
                field_val = request.POST[field]
                if 'Info' not in field and field_val == '1' or field_val == '0':
                    if (field + 'Info') in fields:
                        field_text = fields[field + 'Info']
                    else:
                        field_text = field_val
                    pm = pat_medHis.filter(info_type__exact = field)
                    if pm.count() > 0:
                        pm = pat_medHis.get(info_type = field)
                        if pm.info_type in fields and \
                            request.POST[pm.info_type] == '0':
                            pm.delete()
                        else:
                           if pm.info_type in fields and \
                                fields[pm.info_type] == '1' and \
                                len(field_text) > 1 and \
                                pm.med_history != field_text:
                            pm.med_history = field_text
                            pm.save()
                    else:
                        if pm.count() == 0 and field_val == '1':
                            pm = PatientMedHistory(
                                user_name = user,
                                info_type = field,
                                med_history = field_text)
                            pm.save()

            for pm in pat_medHis:
                if pm.info_type not in fields:
                    pm.delete()

            return render(request, "dashboard/index.html")
    return render(request, "login/index.html")

def readData(request):
    if request.session.get('member_id'):
        user = request.session.get('member_id')
        pat_medHis = PatientMedHistory.objects \
            .filter(user_name__exact = user);
        medHis = MedHistoryInfo.objects \
            .order_by('med_history_id');

        if pat_medHis.count() == 0:
            return render(request, "patientmedicalhistory/index.html", {"medHis_info":{"medhis_list": medHis,},})
        else:
            objs = dict()
            for pm in pat_medHis:
                objs.update({pm.info_type : pm.med_history})
        return render(request, "patientmedicalhistory/modify.html", {"medHis_info":{"pat_medhis_list": objs,"medhis_list": medHis,},})
    return render(request, "login/index.html")

patientmedicalhistory/templates/patientmedicalhistory/index.html
{% extends "patientmedicalhistory/layout.html" %}
{% load static %}
{% block title %}Patient's Medical History{% endblock %}

{% block head %}
    <script src="{% static 'patientmedicalhistory/jslib/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'patientmedicalhistory/jslib/jquery.validate.min.js' %}"></script>
{% endblock %}

{% block scripts %}

    <script type="text/javascript">
	$(document).ready(function() {
		<!-- check all the radio buttons in the symptoms section -->
		$('#chkall').on('click', function() {
			if ($(this).is(':checked'))
				$("#symptoms input[type=radio][value=0]").attr("checked", "checked");
			else
				$("#symptoms input[type=radio][value=0]").removeAttr("checked");
		});
		
		<!-- Validation -->
		$('#medicalhistoryform').on('submit', function(e) {
			<!--check all the radio button see if they are selected-->

            let yesRadioBtns = $("input[type=radio][value=1]");
            let noRadioBtns = $("input[type=radio][value=0]");
            let len = yesRadioBtns.length;
            let isRadioBtnsChecked = true;
            for (let i = 0; i < len - 1; i += 2) {
                isRadioBtnsChecked = isRadioBtnsChecked &&
                    ( (yesRadioBtns.get(i).checked && !noRadioBtns.get(i).checked) ||
                      (!yesRadioBtns.get(i).checked && noRadioBtns.get(i).checked) ) && 
                    ( (yesRadioBtns.get(i + 1).checked && !noRadioBtns.get(i + 1).checked) ||
                      (!yesRadioBtns.get(i + 1).checked && noRadioBtns.get(i + 1).checked) );
                if (len % 2 === 1 && i === (len / 2) + 1) {
                    isRadioBtnsChecked = isRadioBtnsChecked &&
                        ( (yesRadioBtns.get(i + 2).checked && !noRadioBtns.get(i + 2).checked) ||
                          (!yesRadioBtns.get(i + 2).checked && noRadioBtns.get(i + 2).checked) )
                }
            }

			if ( isRadioBtnsChecked ) {
				 
				 <!--validate text box if Yes was chosen-->
				 if ( ($("input[name=physicianCare][value=1]").is(":checked") && $("input[name=physicianCareInfo]").val().length === 0) ||
				 	  ($("input[name=hospitalizedMajorOps][value=1]").is(":checked") && $("input[name=hospitalizedMajorOpsInfo]").val().length === 0) ||
					  ($("input[name=headNeckInjury][value=1]").is(":checked") && $("input[name=headNeckInjuryInfo]").val().length === 0) ||
					  ($("input[name=meds][value=1]").is(":checked") && $("textarea[name=medsInfo]").val().length === 0) ||
					  ($("input[id=allergyOther][value=allergyOther]").is(":checked") && $("input[name=allergyOtherInfo]").val().length === 0) ) {
				 	e.preventDefault();
					alert("The textbox should not be empty if the 'Yes' button or some checkbox was chosen!");
				 }
			} else {
				e.preventDefault();
				alert("Every radio button has to be selected!");
			}
		});
	});
	</script>
{% endblock %}

{% block content %}

{% if medHis_info %}
    {% for medhis in medHis_info.medhis_list %}
        
        {% if medhis.type == "Question" %}
            {% block questionbefore %}
                <li>
            {% endblock %}

            <div class="medical-history-group">
                <div class="medical-history"><label>{{medhis.med_history}}</label></div>
                <div class="choice">
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-yes" value="1">
                    <label>Yes</label>
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-no" value="0">
                    <label>No</label>
                </div>
            </div>

            {% block questionafter %}
                <div class="medical-info">
                <label>If yes</label>   

                {% if medhis.label == "meds" %}         
                    <textarea name="{{medhis.label}}Info" id="{{medhis.label}}Info"></textarea>
                {% else %}
                    <input type="text" name="{{medhis.label}}Info" id="{{medhis.label}}Info">
                {% endif %}

                </div>
                </li>
            {% endblock %}
        {% elif medhis.type == "Choice" %}
            {% block choicebefore %}
                {% if medhis.label == "specialDiet" %}
                    <li class="positioning-1">
                {% elif medhis.label == "phenFenRedux" or medhis.label == "bisphosphonates" %}
                    <li class="rowspan positioning-1">
                {% elif medhis.label == "tobacco" or medhis.label == "controlledSub" %}
                    <li class="rowspan positioning-2">
                {% endif %}
            {% endblock %}

            <div class="medical-history-group">
                <div class="medical-history"><label>{{medhis.med_history}}</label></div>
                <div class="choice">
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-yes" value="1">
                    <label>Yes</label>
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-no" value="0">
                    <label>No</label>
                </div>
            </div>

            {% block choiceafter %}
                {% if medhis.label == "specialDiet" %}
                    <div class="medical-info">
                        <label style="visibility:hidden;">If yes</label>
                        <fieldset>
                            <legend>For women: Are you</legend>
                {% else %}
                    </li>
                {% endif %}
            {% endblock %}
        {% elif medhis.type == "SymptomQuestion" %}
            {% block symptomquestionbefore %}
                {% if medhis.label == "aidsHiv" %}
                    <li class="positioning-2">
                        <div class="symptom-info">
                            <fieldset id="symptoms">
                                <legend>Do you have, or have you had, any of the following?</legend>

                                <div id="checkNo">
                                    <label>Check no for all:</label>
                                    <input type="checkbox" id="chkall" name="chkall">
                                </div>
                    
                                <div class="symptom-info-group">
                {% endif %}
            {% endblock %}

            <div class="medical-history-group">
                <div class="medical-history"><label>{{medhis.med_history}}</label></div>
                <div class="choice">
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-yes" value="1">
                    <label>Yes</label>
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-no" value="0">
                    <label>No</label>
                </div>
            </div>

            {% block symptomquestionafter %}
                {% if medhis.label == "convuls" or medhis.label == "hrtTroubleDis" or medhis.label == "psychCare" %}
                    </div>
                    <div class="divider"></div>
                    <div class="symptom-info-group">
                {% elif medhis.label == "yellJaund" %}
                    </div>
                    </fieldset>
                    </div>
                        <div style="float:right; width:300px; margin-top:5px;">
                            <input type="submit" value="Save">
                            <a class="message" href="{% url 'dashboard:index'%}">
                                <div style="width:38%; display:inline-block; margin-left:4px; padding: 14px; text-align:center; border:1px solid #4CAF50">
                                    Dashboard
                                </div>
                            </a>
                        </div>
                    </li>
                {% endif %}
            {% endblock %}
        {% endif %}
            
        {% if medhis.type == "WomenQuestion" %}
            {% block womenquestionbefore %}
                <div class="women-info">
            {% endblock %}
        
            <input type="checkbox" name="{{medhis.label}}" id="{{medhis.label}}" value="1">
            <label>{{medhis.med_history}}</label>

            {% block womenquestionafter %}
                {% if medhis.label == "oralContr" %}
                    </div>
                    </fieldset>
                    </div>
                    </li>
                {% else %}
                    </div>
                {% endif %}
            {% endblock %}
        {% elif medhis.type == "AllergyQuestion" %}
            {% block allergyquestionbefore %}
                {% if medhis.label == "allergyAspirin" %}
                    <li class="positioning-2">
                        <div class="allergy-info-group">
                            <fieldset id="allergies">
                                <legend>Are you allergic to any of the following?</legend>
                                <div class="allergy-info">
                {% else %} 
                    <div class="allergy-info">
                {% endif %}
            {% endblock %}

            <input type="checkbox" name="{{medhis.label}}" id="{{medhis.label}}" value="1">
            <label>{{medhis.med_history}}</label>

            {% block allergyquestionafter %}
                {% if medhis.label == "allergyOther" %}
                    <input type="text" name="{{medhis.label}}Info" id="{{medhis.label}}Info">
                    </div>
                    </fieldset>
                    </div>
                    </li>
                {% else %}
                    </div>
                {% endif %}
            {% endblock %}
        {% endif %}
        
    {% endfor %}
{% endif %}

{% endblock %}

patientmedicalhistory/templates/patientmedicalhistory/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" type="text/css" href="{% static 'patientmedicalhistory/style.css' %}" />
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    {% block scripts %}{% endblock %}
</head>
<body>
    <div class="medicalhistory-page">
        <div class="form">
            <h1>Patient Medical History :</h1>
            <form action="{% url 'patientmedicalhistory:saveMedHistoryInfo'%}" method="post" id="medicalhistoryform">
                {% csrf_token %}

                <ol class="clearfix">
                    {% block content %}

                        {% block questionbefore %}
                        {% endblock %}

                        {% block questionafter %}
                        {% endblock %}

                        {% block choicebefore %}
                        {% endblock %}

                        {% block choiceafter %}
                        {% endblock %}

                        {% block womenquestionbefore %}
                        {% endblock %}

                        {% block womenquestionafter %}
                        {% endblock %}

                        {% block allergyquestionbefore %}
                        {% endblock %}

                        {% block allergyquestionafter %}
                        {% endblock %}

                        {% block symptomquestionbefore %}
                        {% endblock %}

                        {% block symptomquestionafter %}
                        {% endblock %}

                    {% endblock %}
                </ol>

            </form>
        </div>
    </div>
</body>
</html>

patientmedicalhistory/templates/patientmedicalhistory/modify.html
{% extends "patientmedicalhistory/layout.html" %}
{% load static %}
{% block title %}Patient's Medical History{% endblock %}

{% block head %}
    <script src="{% static 'patientmedicalhistory/jslib/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'patientmedicalhistory/jslib/jquery.validate.min.js' %}"></script>
{% endblock %}

{% block scripts %}
  
    <script type="text/javascript">
        $(document).ready(function() {
            $('input[type=radio][value=0]').attr('checked', 'checked');

            {% if medHis_info.pat_medhis_list %}
                {% for pat_medhis_list_key, pat_medhis_list_val in medHis_info.pat_medhis_list.items %}
                    $("input[name={{pat_medhis_list_key}}][value=1]").attr("checked", "checked");
                    if ("{{pat_medhis_list_val}}".length > 1)
                        $("input[name={{pat_medhis_list_key}}" + "Info]").val("{{pat_medhis_list_val}}");
                {% endfor %}
            {% endif %}
	
            $('#chkall').on('click', function() {
		        if ($(this).is(':checked'))
			        $("#symptoms input[type=radio][value=0]").attr("checked", "checked");
		        else
			        $("#symptoms input[type=radio][value=0]").removeAttr("checked");
	        });

	        <!-- Validation -->
	        $('#medicalhistoryform').on('submit', function(e) {
				 
		        <!--validate text box if 'Yes' was chosen-->
		        if ( ($("input[name=physicianCare][value=1]").is(":checked") && $("input[name=physicianCareInfo]").val().length === 0) ||
			        ($("input[name=hospitalizedMajorOps][value=1]").is(":checked") && $("input[name=hospitalizedMajorOpsInfo]").val().length === 0) ||
			        ($("input[name=headNeckInjury][value=1]").is(":checked") && $("input[name=headNeckInjuryInfo]").val().length === 0) ||
			        ($("input[name=meds][value=1]").is(":checked") && $("textarea[name=medsInfo]").val().length === 0) ||
			        ($("input[id=allergyOther][value=allergyOther]").is(":checked") && $("input[name=allergyOtherInfo]").val().length === 0) ) {
		            e.preventDefault();
		            alert("The textbox should not be empty if the 'Yes' button or some checkbox was chosen!");
		        }

	        });
        });
    </script>

{% endblock %}

{% block content %}

{% if medHis_info %}
    {% for medhis in medHis_info.medhis_list %}
        
        {% if medhis.type == "Question" %}
            {% block questionbefore %}
                <li>
            {% endblock %}

            <div class="medical-history-group">
                <div class="medical-history"><label>{{medhis.med_history}}</label></div>
                <div class="choice">
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-yes" value="1">
                    <label>Yes</label>
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-no" value="0">
                    <label>No</label>
                </div>
            </div>

            {% block questionafter %}
                <div class="medical-info">
                <label>If yes</label>   

                {% if medhis.label == "meds" %}         
                    <textarea name="{{medhis.label}}Info" id="{{medhis.label}}Info"></textarea>
                {% else %}
                    <input type="text" name="{{medhis.label}}Info" id="{{medhis.label}}Info">
                {% endif %}

                </div>
                </li>
            {% endblock %}
        {% elif medhis.type == "Choice" %}
            {% block choicebefore %}
                {% if medhis.label == "specialDiet" %}
                    <li class="positioning-1">
                {% elif medhis.label == "phenFenRedux" or medhis.label == "bisphosphonates" %}
                    <li class="rowspan positioning-1">
                {% elif medhis.label == "tobacco" or medhis.label == "controlledSub" %}
                    <li class="rowspan positioning-2">
                {% endif %}
            {% endblock %}

            <div class="medical-history-group">
                <div class="medical-history"><label>{{medhis.med_history}}</label></div>
                <div class="choice">
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-yes" value="1">
                    <label>Yes</label>
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-no" value="0">
                    <label>No</label>
                </div>
            </div>

            {% block choiceafter %}
                {% if medhis.label == "specialDiet" %}
                    <div class="medical-info">
                        <label style="visibility:hidden;">If yes</label>
                        <fieldset>
                            <legend>For women: Are you</legend>
                {% else %}
                    </li>
                {% endif %}
            {% endblock %}
        {% elif medhis.type == "SymptomQuestion" %}
            {% block symptomquestionbefore %}
                {% if medhis.label == "aidsHiv" %}
                    <li class="positioning-2">
                        <div class="symptom-info">
                            <fieldset id="symptoms">
                                <legend>Do you have, or have you had, any of the following?</legend>

                                <div id="checkNo">
                                    <label>Check no for all:</label>
                                    <input type="checkbox" id="chkall" name="chkall">
                                </div>
                    
                                <div class="symptom-info-group">
                {% endif %}
            {% endblock %}

            <div class="medical-history-group">
                <div class="medical-history"><label>{{medhis.med_history}}</label></div>
                <div class="choice">
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-yes" value="1">
                    <label>Yes</label>
                    <input type="radio" name="{{medhis.label}}" id="radio-btn-group-{{medhis.label}}-no" value="0">
                    <label>No</label>
                </div>
            </div>

            {% block symptomquestionafter %}
                {% if medhis.label == "convuls" or medhis.label == "hrtTroubleDis" or medhis.label == "psychCare" %}
                    </div>
                    <div class="divider"></div>
                    <div class="symptom-info-group">
                {% elif medhis.label == "yellJaund" %}
                    </div>
                    </fieldset>
                    </div>
                        <div style="float:right; width:300px; margin-top:5px;">
                            <input type="submit" value="Save">
                            <a class="message" href="{% url 'dashboard:index'%}">
                                <div style="width:38%; display:inline-block; margin-left:4px; padding: 14px; text-align:center; border:1px solid #4CAF50">
                                    Dashboard
                                </div>
                            </a>
                        </div>
                    </li>
                {% endif %}
            {% endblock %}
        {% endif %}
            
        {% if medhis.type == "WomenQuestion" %}
            {% block womenquestionbefore %}
                <div class="women-info">
            {% endblock %}
        
            <input type="checkbox" name="{{medhis.label}}" id="{{medhis.label}}" value="1">
            <label>{{medhis.med_history}}</label>

            {% block womenquestionafter %}
                {% if medhis.label == "oralContr" %}
                    </div>
                    </fieldset>
                    </div>
                    </li>
                {% else %}
                    </div>
                {% endif %}
            {% endblock %}
        {% elif medhis.type == "AllergyQuestion" %}
            {% block allergyquestionbefore %}
                {% if medhis.label == "allergyAspirin" %}
                    <li class="positioning-2">
                        <div class="allergy-info-group">
                            <fieldset id="allergies">
                                <legend>Are you allergic to any of the following?</legend>
                                <div class="allergy-info">
                {% else %} 
                    <div class="allergy-info">
                {% endif %}
            {% endblock %}

            <input type="checkbox" name="{{medhis.label}}" id="{{medhis.label}}" value="1">
            <label>{{medhis.med_history}}</label>

            {% block allergyquestionafter %}
                {% if medhis.label == "allergyOther" %}
                    <input type="text" name="{{medhis.label}}Info" id="{{medhis.label}}Info">
                    </div>
                    </fieldset>
                    </div>
                    </li>
                {% else %}
                    </div>
                {% endif %}
            {% endblock %}
        {% endif %}
        
    {% endfor %}
{% endif %}

{% endblock %}